* Emacs settings.

** Functions

*** Assign yes/no to y/n.
#+BEGIN_SRC emacs-lisp
  (defalias 'yes-or-no-p 'y-or-n-p)
#+END_SRC

*** Turn auto generation of backup file off.
#+BEGIN_SRC emacs-lisp
  (setq make-backup-files nil)
#+END_SRC

*** Turn auto save off.
#+BEGIN_SRC emacs-lisp
  (setq auto-sace-default nil)
#+END_SRC

*** Turn off the annoying bell.
#+BEGIN_SRC emacs-lisp
  (setq ring-bell-function 'ignore)
#+END_SRC

*** Kill a WHOLE word.
#+BEGIN_SRC emacs-lisp
  (defun kill-whole-word ()
    (interactive)
    (backward-word)
    (kill-word 1))
#+END_SRC



** Appearance

*** Hide startup message.
#+BEGIN_SRC emacs-lisp
  (setq inhibit-startup-message t)
#+END_SRC

*** Hide tool bar.
#+BEGIN_SRC emacs-lisp
  (tool-bar-mode -1)
#+END_SRC

*** Hide menu bar.
#+BEGIN_SRC emacs-lisp
  (menu-bar-mode -1)
#+END_SRC

*** Hide scroll bar.
#+BEGIN_SRC emacs-lisp
  (scroll-bar-mode -1)
#+END_SRC

*** Split windows horizontally on startup.
#+BEGIN_SRC emacs-lisp
  (split-window-horizontally)
#+END_SRC

*** Maximize windows on startup.
#+BEGIN_SRC emacs-lisp
  (add-to-list 'default-frame-alist '(fullscreen . maximized))
#+END_SRC

*** Turn off blinking of the cursor.
#+BEGIN_SRC emacs-lisp
  (blink-cursor-mode -1)
#+END_SRC


** Keyboard-shortcuts

*** Removing KBD Bindings.

**** Used for moving between sentences.
#+BEGIN_SRC emacs-lisp
  (global-set-key (kbd "M-a") nil)
#+END_SRC

**** Used for 'other-window function.
#+BEGIN_SRC emacs-lisp
  (global-set-key (kbd "C-x o") nil)
#+END_SRC

**** Used for deleting half part of a word.
#+BEGIN_SRC emacs-lisp
  (global-set-key (kbd "M-d") nil)
  (global-set-key (kbd "C-<backspace>") nil)
#+END_SRC
 

*** Move to the indentation's starting point.
#+BEGIN_SRC emacs-lisp
  (global-set-key (kbd "M-a") 'back-to-indentation)
#+END_SRC

*** Compile using user commands.
#+BEGIN_SRC emacs-lisp
  (global-set-key (kbd "C-.") 'compile)
#+END_SRC

*** Recompile using previous ocmmands.
#+BEGIN_SRC emacs-lisp
  (global-set-key (kbd "C-,") 'recompile)
#+END_SRC

*** Loads ansi-terminal in current frame.
#+BEGIN_SRC emacs-lisp
  (global-set-key (kbd "C--") 'ansi-term)
#+END_SRC

*** Switch windows.
#+BEGIN_SRC emacs-lisp
  (global-set-key (kbd "C-;") 'other-window)
#+END_SRC

*** Kill a whole word.
#+BEGIN_SRC emacs-lisp
  (global-set-key (kbd "M-d") 'kill-whole-word)
#+END_SRC


* Tweaks for Programming.

** Functions

*** Enable navigation on camelCaseLetters.
#+BEGIN_SRC emacs-lisp
  (add-hook 'c-mode-hook 'subword-mode)
  (add-hook 'c++-mode-hook 'subword-mode)
#+END_SRC


** Appearance

*** Autocomplete symbols.
#+BEGIN_SRC emacs-lisp
(electric-pair-mode t)
#+END_SRC

*** Show matching pair of parenthesis.
#+BEGIN_SRC emacs-lisp
  (show-paren-mode t)
#+END_SRC

*** Remove the delay to show matching pair of parenthesis.
#+BEGIN_SRC emacs-lisp
  (setq show-paren-delay nil)
#+END_SRC

*** Highlight the line where the cursor lies.

#+BEGIN_SRC emacs-lisp
  (when window-system (global-hl-line-mode t))
#+END_SRC

*** Change the default font.
#+BEGIN_SRC emacs-lisp
  (set-default-font "Space Mono 10" nil t)
#+END_SRC

*** Change cursor's color.
#+BEGIN_SRC emacs-lisp
  (set-cursor-color "#ffffff")
#+END_SRC


* Ansi-Term

** Ansi-Term is kind of similar to the regular terminal.

- Use's bash by default.

#+BEGIN_SRC emacs-lisp
  (defvar my-term-shell "/bin/bash")
  (defadvice ansi-term (before force-bash)
    (interactive (list my-term-shell)))
  (ad-activate 'ansi-term)
#+END_SRC

* Avy

** Avy is used for manipulating strings and navigation.

#+BEGIN_SRC emacs-lisp
  (use-package avy
    :ensure t
    :bind
    ("M-s" . avy-goto-char))
#+END_SRC

* Company

** Company is used as an auto-completion.

- Company runs automatically on C, C++, & Emacs-lisp files.
- Default keybindings for the popup navigation has been changed.

#+BEGIN_SRC emacs-lisp
  (use-package company
    :ensure t
    :init
    (add-hook 'emacs-lisp-mode-hook 'company-mode)
    (add-hook 'c-mode-hook 'company-mode)
    (add-hook 'c++-mode-hook 'company-mode)
    :config
    (setq company-idle-delay 0)
    (define-key company-active-map (kbd "M-n") nil)
    (define-key company-active-map (kbd "M-p") nil)
    (define-key company-active-map (kbd "C-n") #'company-select-next)
    (define-key company-active-map (kbd "C-p") #'company-select-previous))
#+END_SRC

* Elpy

** Elpy is an package to turn emacs into Python IDE.

- Uses python3 as it's interpreter and for rpc.

#+BEGIN_SRC emacs-lisp
  ;(use-package elpy
  ;  :ensure t
  ;  :config
  ;  (enable-elpy)
  ;  (setq elpy-rpc-python-command "python3")
  ;  (setq python-shell-interpreter "python3")
#+END_SRC

* Helm

** Used for showing suggestions in a popup box.

- Helm's window pops up in the same window where it was called.
- Helm's window auto resizes.
- Overwrite's some shortcuts as seen below.

#+BEGIN_SRC emacs-lisp
  (use-package helm
    :ensure t
    :config
    (setq helm-split-window-in-side-p t)
    (helm-autoresize-mode t)
    (define-key helm-map (kbd "<tab>") 'helm-execute-persistent-action)
    (global-set-key (kbd "C-x b") 'helm-buffers-list)
    (global-set-key (kbd "C-=") 'helm-bookmarks)
    (global-set-key (kbd "M-x") 'helm-M-x)
    (global-set-key (kbd "M-y") 'helm-show-kill-ring)
    (global-set-key (kbd "C-s") 'helm-occur)
    (global-set-key (kbd "C-x C-f") 'helm-find-files))

  (use-package helm-cscope
    :ensure t
    )
#+END_SRC

* Mark-multiple

** Helps to mark the same type of string and edit them at once.

#+BEGIN_SRC emacs-lisp
  (use-package mark-multiple
    :ensure t
    :bind
    ("C-'" . 'mark-next-like-this))
#+END_SRC

* Org

** Used for organizing various things.

- Automatically indents org-mode.
- Source window shows in the current window.

#+BEGIN_SRC emacs-lisp
    (use-package org
      :ensure t
      :init 
      (setq org-src-window-setup 'current-window)
      (add-hook 'org-mode-hook 'org-indent-mode))
#+END_SRC
    
* Powerline-mode

** Makes the status-bar look cool.

- Uses the default theme.

#+BEGIN_SRC emacs-lisp
  (use-package powerline
    :ensure t
    :config
    (powerline-default-theme))
#+END_SRC

* Rainbow

** A minor mode which shows color of the regular/hexadecimal text.

- Needs to be turned on when it is needed.

#+BEGIN_SRC emacs-lisp
  (use-package rainbow-mode
    :ensure t)
#+End_SRC 

* Xscope

** For navigation of source code and it's implementation.

#+BEGIN_SRC emacs-lisp
  (use-package xcscope
    :ensure t
    :bind
    ("C-<f5>" . cscope-find-this-symbol)
    ("C-<f1>" . cscope-display-buffer-toggle)
    ("C-<f2>" . cscope-display-buffer))
#+END_SRC

